version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:80
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/00001_init.sql
    environment:
      POSTGRES_PASSWORD: example
    